/**
 * Error codes for API responses
 * These codes are used by the frontend to display localized error messages
 */
export enum ErrorCode {
  // Config errors
  CONFIG_GET_FAILED = 'CONFIG_GET_FAILED',
  CONFIG_UPDATE_FAILED = 'CONFIG_UPDATE_FAILED',
  CONFIG_UPDATE_SUCCESS = 'CONFIG_UPDATE_SUCCESS',
  CONFIG_INVALID = 'CONFIG_INVALID',
  CONFIG_VALIDATE_FAILED = 'CONFIG_VALIDATE_FAILED',
  CONFIG_BACKUP_SUCCESS = 'CONFIG_BACKUP_SUCCESS',
  CONFIG_BACKUP_FAILED = 'CONFIG_BACKUP_FAILED',
  CONFIG_RESTORE_SUCCESS = 'CONFIG_RESTORE_SUCCESS',
  CONFIG_RESTORE_FAILED = 'CONFIG_RESTORE_FAILED',
  CONFIG_BACKUP_PATH_INVALID = 'CONFIG_BACKUP_PATH_INVALID',
  // Config validation errors
  CONFIG_VALIDATION_PIXIV_REQUIRED = 'CONFIG_VALIDATION_PIXIV_REQUIRED',
  CONFIG_VALIDATION_PIXIV_CLIENT_ID_REQUIRED = 'CONFIG_VALIDATION_PIXIV_CLIENT_ID_REQUIRED',
  CONFIG_VALIDATION_PIXIV_REFRESH_TOKEN_REQUIRED = 'CONFIG_VALIDATION_PIXIV_REFRESH_TOKEN_REQUIRED',
  CONFIG_VALIDATION_TARGETS_REQUIRED = 'CONFIG_VALIDATION_TARGETS_REQUIRED',
  CONFIG_VALIDATION_TARGET_TYPE_REQUIRED = 'CONFIG_VALIDATION_TARGET_TYPE_REQUIRED',
  CONFIG_VALIDATION_TARGET_TYPE_INVALID = 'CONFIG_VALIDATION_TARGET_TYPE_INVALID',
  CONFIG_VALIDATION_TARGET_LIMIT_INVALID = 'CONFIG_VALIDATION_TARGET_LIMIT_INVALID',
  CONFIG_VALIDATION_STORAGE_REQUIRED = 'CONFIG_VALIDATION_STORAGE_REQUIRED',
  CONFIG_VALIDATION_DOWNLOAD_DIRECTORY_REQUIRED = 'CONFIG_VALIDATION_DOWNLOAD_DIRECTORY_REQUIRED',
  CONFIG_VALIDATION_CRON_REQUIRED = 'CONFIG_VALIDATION_CRON_REQUIRED',
  CONFIG_VALIDATION_CRON_INVALID = 'CONFIG_VALIDATION_CRON_INVALID',

  // Download errors
  DOWNLOAD_TASK_ALREADY_RUNNING = 'DOWNLOAD_TASK_ALREADY_RUNNING',
  DOWNLOAD_START_SUCCESS = 'DOWNLOAD_START_SUCCESS',
  DOWNLOAD_START_FAILED = 'DOWNLOAD_START_FAILED',
  DOWNLOAD_STOP_SUCCESS = 'DOWNLOAD_STOP_SUCCESS',
  DOWNLOAD_STOP_FAILED = 'DOWNLOAD_STOP_FAILED',
  DOWNLOAD_TASK_NOT_FOUND = 'DOWNLOAD_TASK_NOT_FOUND',
  DOWNLOAD_STATUS_FAILED = 'DOWNLOAD_STATUS_FAILED',
  DOWNLOAD_TASK_ID_REQUIRED = 'DOWNLOAD_TASK_ID_REQUIRED',
  DOWNLOAD_LOGS_FAILED = 'DOWNLOAD_LOGS_FAILED',
  DOWNLOAD_HISTORY_FAILED = 'DOWNLOAD_HISTORY_FAILED',
  DOWNLOAD_RUN_ALL_START_SUCCESS = 'DOWNLOAD_RUN_ALL_START_SUCCESS',
  DOWNLOAD_RUN_ALL_START_FAILED = 'DOWNLOAD_RUN_ALL_START_FAILED',
  DOWNLOAD_INCOMPLETE_GET_FAILED = 'DOWNLOAD_INCOMPLETE_GET_FAILED',
  DOWNLOAD_INCOMPLETE_DELETE_ALL_SUCCESS = 'DOWNLOAD_INCOMPLETE_DELETE_ALL_SUCCESS',
  DOWNLOAD_INCOMPLETE_DELETE_ALL_FAILED = 'DOWNLOAD_INCOMPLETE_DELETE_ALL_FAILED',
  DOWNLOAD_INCOMPLETE_DELETE_SUCCESS = 'DOWNLOAD_INCOMPLETE_DELETE_SUCCESS',
  DOWNLOAD_INCOMPLETE_DELETE_FAILED = 'DOWNLOAD_INCOMPLETE_DELETE_FAILED',
  DOWNLOAD_INCOMPLETE_TASK_ID_INVALID = 'DOWNLOAD_INCOMPLETE_TASK_ID_INVALID',
  DOWNLOAD_DATABASE_NOT_CONFIGURED = 'DOWNLOAD_DATABASE_NOT_CONFIGURED',
  DOWNLOAD_DATABASE_INIT_FAILED = 'DOWNLOAD_DATABASE_INIT_FAILED',
  DOWNLOAD_DATABASE_TEST_SUCCESS = 'DOWNLOAD_DATABASE_TEST_SUCCESS',
  DOWNLOAD_DATABASE_TEST_FAILED = 'DOWNLOAD_DATABASE_TEST_FAILED',
  DOWNLOAD_RESUME_TAG_TYPE_REQUIRED = 'DOWNLOAD_RESUME_TAG_TYPE_REQUIRED',
  DOWNLOAD_RESUME_TARGET_NOT_FOUND = 'DOWNLOAD_RESUME_TARGET_NOT_FOUND',
  DOWNLOAD_RESUME_SUCCESS = 'DOWNLOAD_RESUME_SUCCESS',
  DOWNLOAD_RESUME_FAILED = 'DOWNLOAD_RESUME_FAILED',
  DOWNLOAD_RANDOM_START_SUCCESS = 'DOWNLOAD_RANDOM_START_SUCCESS',
  DOWNLOAD_RANDOM_START_FAILED = 'DOWNLOAD_RANDOM_START_FAILED',

  // File errors
  FILE_LIST_FAILED = 'FILE_LIST_FAILED',
  FILE_PATH_INVALID = 'FILE_PATH_INVALID',
  FILE_PATH_REQUIRED = 'FILE_PATH_REQUIRED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_IS_DIRECTORY = 'FILE_IS_DIRECTORY',
  FILE_READ_FAILED = 'FILE_READ_FAILED',
  FILE_PREVIEW_FAILED = 'FILE_PREVIEW_FAILED',
  FILE_DELETE_SUCCESS = 'FILE_DELETE_SUCCESS',
  FILE_DELETE_FAILED = 'FILE_DELETE_FAILED',
  FILE_NORMALIZE_FAILED = 'FILE_NORMALIZE_FAILED',

  // Auth errors
  AUTH_STATUS_FAILED = 'AUTH_STATUS_FAILED',
  AUTH_USERNAME_PASSWORD_REQUIRED = 'AUTH_USERNAME_PASSWORD_REQUIRED',
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_REFRESH_TOKEN_REQUIRED = 'AUTH_REFRESH_TOKEN_REQUIRED',
  AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS',
  AUTH_REFRESH_FAILED = 'AUTH_REFRESH_FAILED',
  AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED',

  // Stats errors
  STATS_OVERVIEW_FAILED = 'STATS_OVERVIEW_FAILED',
  STATS_DOWNLOADS_FAILED = 'STATS_DOWNLOADS_FAILED',
  STATS_TAGS_FAILED = 'STATS_TAGS_FAILED',
  STATS_AUTHORS_FAILED = 'STATS_AUTHORS_FAILED',

  // Logs errors
  LOGS_GET_FAILED = 'LOGS_GET_FAILED',
  LOGS_CLEAR_SUCCESS = 'LOGS_CLEAR_SUCCESS',
  LOGS_CLEAR_FAILED = 'LOGS_CLEAR_FAILED',
}

/**
 * Success codes for API responses
 */
export enum SuccessCode {
  // These are handled by error codes with _SUCCESS suffix
}

